name: Build

run-name: Build ${{ github.ref_name }}

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Build

    env:
      NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
      NGROK_HTTP_EDGE: ${{ secrets.NGROK_HTTP_EDGE }}
      NGROK_TCP_EDGE: ${{ secrets.NGROK_TCP_EDGE }}
      NGROK_API_KEY: ${{ secrets.NGROK_API_KEY }}
      NGROK_HTTP_EDGE_ENDPOINT: ${{ secrets.NGROK_HTTP_EDGE_ENDPOINT }}
      NGROK_TCP_EDGE_ENDPOINT: ${{ secrets.NGROK_TCP_EDGE_ENDPOINT }}

    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ "3.12" ]
        include:
          - python-version: "3.8"
            os: ubuntu-latest
          - python-version: "3.9"
            os: ubuntu-latest
          - python-version: "3.10"
            os: ubuntu-latest
          - python-version: "3.11"
            os: ubuntu-latest
          - python-version: "pypy-3.9"
            os: ubuntu-latest
          - python-version: "pypy-3.10"
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: make install
      - name: Test
        run: make test

  call-validate:
    uses: alexdlaird/pyngrok/.github/workflows/validate.yml@main
    secrets: inherit

  automerge:
    name: "Auto Approve"
    needs: [build, call-validate]

    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          target: major
          use-github-auto-merge: true