name: "Nightly Build"

run-name: "Nightly Build ${{ github.ref_name }}"

on:
  schedule:
    - cron: "0 9 * * *"

jobs:
  call-build:
    uses: alexdlaird/pyngrok/.github/workflows/build.yml@main
    secrets: inherit