name: Test Docker Trigger

on:
  workflow_dispatch:

jobs:
  release:
    name: Release

    env:
      FORCE_COLOR: 1
      PYTHONUNBUFFERED: 1

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Last Step
        run: |
          gh release create -R alexdlaird/pyngrok-docker 7.3.0 --notes "Pre-built containers for <a href="https://pypi.org/project/pyngrok/7.3.0">pyngrok==7.3.0</a>."
        env:
          GH_TOKEN: ${{ secrets.PYNGROK_DOCKER_GITHUB_TOKEN }}
