name: Validate

on:
  workflow_call:

jobs:
  validate:
    name: Validate

    env:
      FORCE_COLOR: 1
      NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
      NGROK_API_KEY: ${{ secrets.NGROK_API_KEY }}
      NGROK_SUBDOMAIN: ${{ github.repository_owner }}
      NGROK_SKIP_TEST_RESOURCE_TEARDOWN: true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Build test coverage
        run: make install test
      - name: Build docs
        run: make docs
      - name: Check code
        run: make check
      - name: Validate package
        run: make local
      - name: Test downstream
        run: make test-downstream
      - name: Upload test coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./build/coverage
      - name: Upload test results
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./build/test-results